npmScopes:
  greenfinity:
    npmPublishRegistry: "https://npm.greenfinity.hu"
    npmRegistryServer: "https://npm.greenfinity.hu"

packageExtensions:
  jest-circus@*:
    dependencies:
      "@babel/runtime": "*"
  jest-environment-node@*:
    dependencies:
      "@babel/runtime": "*"
  jest-runner@*:
    dependencies:
      "@babel/runtime": "*"
  rescript@*:
    dependencies:
      "@babel/runtime": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-rescript.cjs
    spec: "https://github.com/reason-seoul/yarn-plugin-rescript/releases/download/v0.0.0-202110060902-01aad45/plugin-rescript.js"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
